spring:
  datasource:
    url: jdbc:mysql://47.112.27.55:3306/information?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: test
    password: X9xky?8lxEK!
    driver-class-name: com.mysql.cj.jdbc.Driver
